# Generated by Django 4.2.2 on 2023-06-13 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', '超管'), ('manager', '管理员'), ('staff', '员工')], default='staff', max_length=16, verbose_name='用户角色'),
        ),
    ]
