# Generated by Django 4.2.2 on 2023-06-13 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='monetary_unit',
            field=models.CharField(default='USDT', max_length=15, verbose_name='币种'),
        ),
        migrations.AlterField(
            model_name='product',
            name='strategy',
            field=models.CharField(max_length=50, null=True, verbose_name='策略'),
        ),
    ]
